### PR TITLE
feat: add new launcher icon

### PR DESCRIPTION
**Pull request by danielgolden**
Someone asked me for the "logo" for this project yesterday, and I noticed that no custom icon had ever been created for it so I created a quick icon for the launcher. Sent it to them already, so they're good to go, but figured we might as well add it here. Open to feedback if it's not quite appropriate. Here's what it looks like on the NR1 homepage:

Captura de Pantalla 2019-11-01 a la(s) 7 01 21 a  m

### CODE REVIEW

**Comment by danielgolden** [comment]
I thought this was Kav's repo, but it's saying that he doesn't have write access? Who's app is this?

**Comment by Kav91** [comment]
@danielgolden it is mine, so all good I can merge this in. Thanks for the icon it looks great!

**Pull request merged**
